#!/bin/sh
NAME='ourword-demo'
HERE=`pwd`
TARGETS='hardy'
#TARGETS='hardy intrepid'
REVISION=`echo $BUILD_NUMBER | sed -e 's/:.*$//'`
MAJOR=`sed -e 's/\.${revision}//' build/version.txt`
rm -fr output/build
mkdir -p output/build
cd output/build
cp ../linux/mono/2.0/Debug/${NAME}-src-${MAJOR}.${REVISION}.tar.gz ${NAME}_${MAJOR}.${REVISION}.orig.tar.gz
mkdir ${NAME}-${MAJOR}.${REVISION}
cd ${NAME}-${MAJOR}.${REVISION}
tar xzf ../${NAME}_${MAJOR}.${REVISION}.orig.tar.gz
cp -r ../../../debian-src debian
export DEBSIGN_KEYID="mono teamcity"
dch -v $MAJOR.$REVISION-1sil1 "Daily Build"
/home/mono/bin/mpdebuild --vadd .%d --distrib "$TARGETS" --configfile /home/mono/pbuilder/pbuilderrc-%d-new --auto-debsign
#/home/mono/bin/mpdebuild --vadd .%d --distrib "$TARGETS" --use-pdebuild-internal --configfile /home/mono/pbuilder/pbuilderrc-%d-new --auto-debsign
#/home/mono/bin/mdput -d ~/pbuilder/results -t PALASO- -f ${NAME}_${MAJOR}.${REVISION}\*.changes $TARGETS
